### ISSUE TITLE
[RFC] Proposed release management workflow

### ISSUE THREAD

**Issue by MatthiasValvekens** [pyauth/python-pkcs11#203]
Hi all, as mentioned in the comments of #202, I have some thoughts about how to manage this project's release flow, with the ultimate goal being to get this project back on track in terms of release pace.

Full disclosure: I care about this mainly because I depend on `python-pkcs11` in [pyHanko](https://github.com/MatthiasValvekens/pyHanko/) for PKCS#11 signature creation support.

# Proposal

To lead with the conclusion: I'm of the opinion that `python-pkcs11` should have its release flow done completely within GitHub Actions, and that the publication to PyPI should be done with a [trusted publisher](https://docs.pypi.org/trusted-publishers/) straight from GitHub Actions.

# Rationale

## Reproducibility & standardisation

Building a project that involves C extensions with platform-dependent code is hard. Doing it consistently is even harder. This can be dealt with in several ways:

 - Only releasing a source distribution. This pushes some complexity to the downstream user, and requires build tooling at install time, which is not ideal for obvious reasons. It's also quite likely that compilation issues for less commonly used platforms would only be caught by end-users in this scenario.

 - Having a maintainer build wheels on several platforms for every release. This is labour-intensive and error-prone. The risk that releases languish because of maintainer's lack of time is also much greater.

 - Doing the builds in GitHub Actions. This gets you reproducibility & (relative) ease of doing multiplatform builds, at the cost of some initial setup & workflow maintenance overhead.

I'm obviously advocating for the 3rd approach here.

## Multiplatform builds

Building wheels for `python-pkcs11` on multiple platforms using the `cibuildwheel` action is pretty easy:

```yaml
name: Build wheels
on:
  workflow_dispatch: {}
jobs:
  run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          [ubuntu-latest, ubuntu-24.04-arm, windows-latest, windows-11-arm, macos-latest]
    steps:
      - name: Acquire sources
        uses: actions/checkout@v4
      - name: Build wheels
        uses: pypa/cibuildwheel@v3.0.0
      - uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl
```

## PyPI trusted publishers & release process governance

Traditionally, doing releases to PyPI from CI required configuring a long-lived PyPI access token in GitHub secrets, which comes with a bunch of caveats to manage.
In this day and age, that's no longer necessary: PyPI has "batteries included" support for doing releases straight from GitHub Actions _without_ having to do any credential management yourself. You can read more about this in in PyPI's documentation on [trusted publishers](https://docs.pypi.org/trusted-publishers/).

To give a real-life example: PyPI's entry for PyHanko has a trusted publisher that allows publication from the `release.yml` workflow in `MatthiasValvekens/pyHanko` as long as the upload job runs in the `release` environment.

Here, "environment" refers to the GitHub Actions environment in which the release step is executed. Environments are useful for more than just secrets / release variable management:

 - In the repository settings, I have a rule that running workflows in the `release` environment requires manual admin approval/review.

 - To allow for testing release workflow changes, I have an equivalent set up on TestPyPI that is more or less identical to the one on PyPI, but with the target environment set to `test-release`.

 - The environment is also included in SLSA provenance data, if that's something you're interested in.

So, long story short, this setup allows for running releases with the click of a button, while still having some guard rails around pushing releases to PyPI.

Effectively, this moves most of the release governance burden from PyPI to GitHub, which should also make things easier for @danni.

## Testing improvements

I think it would also be useful to run the test suite against the output of the `cibuildwheel` step as a matter of routine. There are some tradeoffs here: it's probably not feasible to test all interesting combinations, and in a regular CI run you don't necessarily want to build all the wheels for a full release every time, but even selectively building some wheels to test will allow us to catch build problems early on.

---

# Next steps

If you're on board with this, I'm happy to put together the workflow files necessary to pull this off, but there are a few things that will require admin assistance no matter what.

 - On the PyPI side, someone will have to set up the trusted publisher. I'm not sure if @kislyuk would be able to do that, we might need @danni.

 - On the GitHub side, @kislyuk would probably have to handle setting up a `release` and `test-release` environment in the GitHub repository settings.

Thoughts?
